import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState } from "react";
import absoluteUrl from "next-absolute-url";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const copyToClipboard = (newUrl) => {
  navigator.clipboard.writeText(newUrl);

  toast.success("Copied to clipboard");
};

const Output = (newUrl) => {
  return (
    <div className='output'>
      <div className='new_url'>{newUrl.newUrl}</div>
      <button on onClick={() => copyToClipboard(newUrl.newUrl)}>
        Copy to clipboard
      </button>
    </div>
  );
};

const Home = (langkey) => {
  const [url, setUrl] = useState("");
  const [newUrl, setNewUrl] = useState("");

  const checkUrl = async (e) => {
    e.preventDefault();

    const { data: short_url } = await axios.post("/api/url", { long_url: url });
    setNewUrl(`${langkey.langkey}/api/${short_url.short_url}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Url shortener</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ToastContainer />
        <h1 className={styles.title}>Url Shortener</h1>

        <form onSubmit={checkUrl}>
          <input
            type='text'
            onChange={(e) => {
              setUrl(e.target.value);
              setNewUrl("");
            }}
            required
            placeholder='Enter url to shorten'
            // pattern='https?://.*'
            pattern='[Hh][Tt][Tt][Pp][Ss]?:\/\/(?:(?:[a-zA-Z\u00a1-\uffff0-9]+-?)*[a-zA-Z\u00a1-\uffff0-9]+)(?:\.(?:[a-zA-Z\u00a1-\uffff0-9]+-?)*[a-zA-Z\u00a1-\uffff0-9]+)*(?:\.(?:[a-zA-Z\u00a1-\uffff]{2,}))(?::\d{2,5})?(?:\/[^\s]*)?'
            // pattern='http(s?)(:\/\/)((www.)?)(([^.]+)\.)?([a-zA-z0-9\-_]+)(.com|.net|.gov|.org|.in|.co.uk|.dev|.ie|.ca|.me|.ai|.co|io)(\/[^\s]*)?'
            onInvalid={() => {
              toast.error(
                "Please enter a valid url.\nUrl must start with http:// or https://"
              );
            }}
          />

          <button type='submit'>Shorten Url</button>
          {newUrl && <Output newUrl={newUrl} />}
        </form>
      </main>
    </div>
  );
};

Home.getInitialProps = async ({ req }) => {
  const { origin } = absoluteUrl(req);
  const apiURL = `${origin}`;
  return { langkey: apiURL };
};

export default Home;
